// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCloudLLMModel(arg1) {
  return window['go']['main']['App']['CreateCloudLLMModel'](arg1);
}

export function DeleteCloudLLMModel(arg1) {
  return window['go']['main']['App']['DeleteCloudLLMModel'](arg1);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetCloudLLMModelByID(arg1) {
  return window['go']['main']['App']['GetCloudLLMModelByID'](arg1);
}

export function GetCloudLLMModels(arg1, arg2) {
  return window['go']['main']['App']['GetCloudLLMModels'](arg1, arg2);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function SendMessageStream(arg1) {
  return window['go']['main']['App']['SendMessageStream'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function ToggleCloudLLMModelEnabled(arg1, arg2) {
  return window['go']['main']['App']['ToggleCloudLLMModelEnabled'](arg1, arg2);
}

export function UpdateCloudLLMModel(arg1) {
  return window['go']['main']['App']['UpdateCloudLLMModel'](arg1);
}
