// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetAppConfig():Promise<config.AppConfig>;

export function GetSetting(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;
